
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author arman
 */
public class MainInterface extends javax.swing.JFrame {

    public static JDesktopPane jDesktopPane_menu;

    public MainInterface() {
        initComponents();
        this.setLocationRelativeTo(null);

        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("MSN INAOE");

        this.setLayout(null);
        jDesktopPane_menu = new JDesktopPane();

        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0, 0, ancho, (alto - 110));
        this.add(jDesktopPane_menu);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        adClientButton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Archivo");

        adClientButton.setText("Agregar cliente");
        adClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adClientButtonActionPerformed(evt);
            }
        });
        jMenu1.add(adClientButton);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Servicios");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adClientButtonActionPerformed
        // 1) Pedir nombre (una sola palabra, solo letras)
        String nombre;
        while (true) {
            nombre = JOptionPane.showInputDialog(
                    this,
                    "Nombre del cliente (una sola palabra):",
                    "Nuevo cliente",
                    JOptionPane.QUESTION_MESSAGE
            );

            if (nombre == null) {
                return; // canceló
            }

            nombre = nombre.trim();

            if (nombre.matches("(?i)^[\\p{L}]+$")) {
                break;
            }

            JOptionPane.showMessageDialog(
                    this,
                    "Escribe solo un nombre (sin espacios ni números).",
                    "Dato inválido",
                    JOptionPane.WARNING_MESSAGE
            );
        }

        // 2) Preguntar protocolo preferido
        String[] opciones = {
            "Clásico (AES-CBC + HMAC)",
            "Post-Quantum (Kyber-512 + AES-GCM)"
        };

        String seleccion = (String) JOptionPane.showInputDialog(
                this,
                "Selecciona el protocolo preferido para este usuario:",
                "Protocolo",
                JOptionPane.QUESTION_MESSAGE,
                null,
                opciones,
                opciones[0]
        );

        if (seleccion == null) {
            return; // canceló
        }

        ProtocolType pref;
        if (seleccion.startsWith("Clásico")) {
            pref = ProtocolType.CLASSIC;
        } else {
            pref = ProtocolType.KYBER_PQ;
        }

        // 3) Generar 5 dígitos aleatorios
        int n = ThreadLocalRandom.current().nextInt(100000);
        String sufijo = String.format("%05d", n);

        // 4) Construir ID
        String id = nombre.toLowerCase() + sufijo;

        // 5) Generar certificado (RSA) - NO depende del protocolo
        try {
            CertManager.UserCertInfo info
                    = CertManager.ensureUserCertificate(id, nombre);
            System.out.println("Certificado generado para " + id
                    + " en " + info.certPath);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo generar el certificado para el usuario " + id,
                    "Error de certificado",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // 6) Crear y mostrar el Internal Frame, pasando el protocolo elegido
        FrameClient frameCliente = new FrameClient(nombre, id, pref);
        jDesktopPane_menu.add(frameCliente);
        frameCliente.setVisible(true);
    }//GEN-LAST:event_adClientButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adClientButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
